#!/bin/bash
#--------------------------------------------------------------------#
#              BrainFuck Interpreter Executable                      #
#--------------------------------------------------------------------#
#              By Aghiles DZIRI, Tanguy INVERNIZZI,                  #
#              Pierre RAINERO and Joel CANCELA VAZ                   #
#                                                                    #
# This file is used to simulate the bfck linux executable from the   #
# bfck jar file. To use it, just launch this script                  #
# with the command ./bfck                                            #
#--------------------------------------------------------------------#

# Name of the path to the jar to launch
DIRECTORY="./target/"

#--------------------------------------------------------------------

# Launch the application
if [ ! -d "$DIRECTORY" ]; then
    mvn install
fi

mvn -q exec:java -Dexec.mainClass="Main" -Dexec.args="$*"
exit $?
