#!/bin/bash
#--------------------------------------------------------------------#
#                   bfck.jar to bfck linux executable                #
#--------------------------------------------------------------------#
#              By Aghiles DZIRI, Tanguy INVERNIZZI,                  #
#              Pierre RAINERO and Joel CANCELA VAZ                   #
#                                                                    #
# This file is used to simulate the bfck linux executable from the   #
# bfck jar file. To use it, just generate your bfck.jar in the       #
# folder /out, and launch this script with the command ./bfck        #
#--------------------------------------------------------------------#

# Name of the jar compiled
jarFileToLaunch="BrainFuckSI3.jar"

# Name of the path to the jar to launch
jarFile="./target/$jarFileToLaunch"

#--------------------------------------------------------------------

# Launch the application
java -jar $jarFile $@
exit $?
